/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    'sesion-slides': SesionSlide;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    ediciones: Ediciones;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sesion-slides".
 */
export interface SesionSlide {
  id: string;
  image: string | Media;
  caption: string;
  path: string;
  showOnHome?: boolean | null;
  order?: number | null;
  coverImage?: string | Media | null;
  gallery?: {
    image: string | Media;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ediciones".
 */
export interface Ediciones {
  id: string;
  hero: {
    title: string;
    backgroundImage?: string | Media | null;
  };
  needSection: {
    title: string;
    subtitle?: string | null;
    bullets?: { text: string; id?: string | null }[] | null;
  };
  packagesSection: {
    title: string;
    subtitle?: string | null;
    backgroundImage?: string | Media | null;
    pricingHeading?: string | null;
    ctaText?: string | null;
    ctaLink?: string | null;
    packages?: {
      title: string;
      price: string;
      subtitle?: string | null;
      features?: { text: string; id?: string | null }[] | null;
      image?: string | Media | null;
      popular?: boolean | null;
      id?: string | null;
    }[] | null;
  };
  pricingTable: {
    packageTabLabel?: string | null;
    eventTabLabel?: string | null;
    packageRows?: {
      type: string;
      quantity?: string | null;
      price: string;
      isPopular?: boolean | null;
      id?: string | null;
    }[] | null;
    eventRows?: {
      service: string;
      details?: string | null;
      price: string;
      id?: string | null;
    }[] | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}